---
title: "Municipal Indicators"
output: 
  html_notebook:
    toc: true
    toc_depth: 2
---
# Demographic

```{r}
                                 ################################################
                                 #       Municipal Indicators For States        #               
                                 ################################################
library(stringr)
library(tidycensus)
library(tidyverse)
library(tigris)
options(tigris_class = "sf",tigris_use_cache = T)
# Get API key 
census_api_key("045944708d514a404443c9f2d227ac8bf6a8f8bd", install = TRUE, overwrite=TRUE)
# Specify the end year 
# This is for 5-year estimates
endyr <- 2018
# List of ACS variables
Var_List <- tidycensus::load_variables(year = endyr, dataset = "acs5", cache = T)
View(Var_List)

                                             #--------------------#
                                             #    DEMOGRAPHIC     #
                                             #--------------------#

##############################################    Population  Size    ###########################################################
States_Data <- list()
j <- 1
for (i in c("MA","ME","CT","NH","RI","VT")) {
  
# Population of the state at Block Group level
Pop.BG <- tidycensus::get_acs(geography = "block group",
													 survey="acs5",
													 state=i,
													 year = endyr,
													 output = "wide",
													 variables = "B01003_001", # Total Population
													 keep_geo_vars = T) %>%
  rename(BG_ID_10 = GEOID,
				 TotalPop_BG = B01003_001E) %>% # B01003_001M is the marginal error
	select(BG_ID_10, NAME, TotalPop_BG)

# Total population of the State
Pop.State <- tidycensus::get_acs(geography = "state",
													 survey="acs5",
													 state=i,
													 year = endyr,
													 output = "wide",
													 variables = "B01003_001", # Total Population
													 keep_geo_vars = T) %>%
  select("NAME", "B01003_001E") %>%
  rename(State = NAME,
         TotalPop_State = B01003_001E) %>% 
  cbind(Pop.BG)

# The Each_State dataframe, which contains info for each state at state level and block group level
Each_State <- Pop.State

##############################################    Population  Age   #############################################################
# Population Age at Block Group level
Age.BG <- tidycensus::get_acs(geography = "block group",
													 survey="acs5",
													 state=i,
													 year = endyr,
													 output = "wide",
													 variables = c("B01001_003","B01001_004","B01001_005","B01001_006",
													 							"B01001_027","B01001_028","B01001_029","B01001_030", # Under 5 years; Between 5 to 17
													 							"B01001_007","B01001_008","B01001_009",
													 							"B01001_010","B01001_011","B01001_012",
													 							"B01001_036","B01001_035","B01001_034",
													 							"B01001_033","B01001_032","B01001_031", # 18 to 24 years; 25 to 34 years
													 							"B01001_013","B01001_014","B01001_015",
													 							"B01001_016","B01001_017","B01001_018","B01001_019",
													 							"B01001_043","B01001_042","B01001_041","B01001_040",
													 							"B01001_039","B01001_038","B01001_037", # 35 to 44 years; 45 to 54 years; 55 to 59 years; 60 to 64 years
													 							"B01001_020","B01001_021","B01001_022",
													 							"B01001_023","B01001_024","B01001_025",
													 							"B01001_044","B01001_045","B01001_046",
													 							"B01001_047","B01001_048","B01001_049"), # 65 to 74 years; 75 years and older
													 keep_geo_vars = T) %>% 
	mutate( # combine variables to make aggregate categories:
		AgeU18 = B01001_003E+B01001_004E+B01001_005E+B01001_006E+B01001_027E+B01001_028E+B01001_029E+B01001_030E, 
				 Age1834 = B01001_007E+B01001_008E+B01001_009E+B01001_010E+B01001_011E+B01001_012E+B01001_036E+B01001_035E+B01001_034E+B01001_033E+B01001_032E+B01001_031E,
				 Age3564 = B01001_013E+B01001_014E+B01001_015E+B01001_016E+B01001_017E+B01001_018E+B01001_019E+B01001_043E+B01001_042E+B01001_041E+B01001_040E+B01001_039E+B01001_038E+B01001_037E,
				 AgeO65 = B01001_020E+B01001_021E+B01001_022E+B01001_023E+B01001_024E+B01001_025E+B01001_044E+B01001_045E+B01001_046E+B01001_047E+B01001_048E+B01001_049E) %>%
  rename(BG_ID_10 = GEOID) %>%
  select(BG_ID_10, AgeU18, Age1834, Age3564, AgeO65) %>%
  rename(AgeU18_BG = AgeU18,
				 Age1834_BG = Age1834,
				 Age3564_BG = Age3564,
				 AgeO65_BG = AgeO65) %>%
  select(BG_ID_10, AgeU18_BG, Age1834_BG, Age3564_BG, AgeO65_BG) %>%
  left_join(Each_State, by="BG_ID_10") %>%
	mutate(AgeU18Per_BG = AgeU18_BG/TotalPop_BG,
				 Age1834Per_BG = Age1834_BG/TotalPop_BG,
				 Age3564Per_BG = Age3564_BG/TotalPop_BG,
				 AgeO65Per_BG = AgeO65_BG/TotalPop_BG)

# Population age at state level
Age.State <- tidycensus::get_acs(geography = "state",
													 survey="acs5",
													 state=i,
													 year = endyr,
													 output = "wide",
													 variables = c("B01001_003","B01001_004","B01001_005","B01001_006",
													 							"B01001_027","B01001_028","B01001_029","B01001_030", # Under 5 years; Between 5 to 17
													 							"B01001_007","B01001_008","B01001_009",
													 							"B01001_010","B01001_011","B01001_012",
													 							"B01001_036","B01001_035","B01001_034",
													 							"B01001_033","B01001_032","B01001_031", # 18 to 24 years; 25 to 34 years
													 							"B01001_013","B01001_014","B01001_015",
													 							"B01001_016","B01001_017","B01001_018","B01001_019",
													 							"B01001_043","B01001_042","B01001_041","B01001_040",
													 							"B01001_039","B01001_038","B01001_037", # 35 to 44 years; 45 to 54 years; 55 to 59 years; 60 to 64 years
													 							"B01001_020","B01001_021","B01001_022",
													 							"B01001_023","B01001_024","B01001_025",
													 							"B01001_044","B01001_045","B01001_046",
													 							"B01001_047","B01001_048","B01001_049"), # 65 to 74 years; 75 years and older
													 keep_geo_vars = T) %>% 
	mutate( # combine variables to make aggregate categories:
		AgeU18_State = B01001_003E+B01001_004E+B01001_005E+B01001_006E+B01001_027E+B01001_028E+B01001_029E+B01001_030E, 
				 Age1834_State = B01001_007E+B01001_008E+B01001_009E+B01001_010E+B01001_011E+B01001_012E+B01001_036E+B01001_035E+B01001_034E+B01001_033E+B01001_032E+B01001_031E,
				 Age3564_State = B01001_013E+B01001_014E+B01001_015E+B01001_016E+B01001_017E+B01001_018E+B01001_019E+B01001_043E+B01001_042E+B01001_041E+B01001_040E+B01001_039E+B01001_038E+B01001_037E,
				 AgeO65_State = B01001_020E+B01001_021E+B01001_022E+B01001_023E+B01001_024E+B01001_025E+B01001_044E+B01001_045E+B01001_046E+B01001_047E+B01001_048E+B01001_049E) %>%
  select(AgeU18_State,Age1834_State,Age3564_State,AgeO65_State) %>%
  cbind(Age.BG) %>%
  mutate(AgeU18Per_State = AgeU18_State/TotalPop_State,
				 Age1834Per_State = Age1834_State/TotalPop_State,
				 Age3564Per_State = Age3564_State/TotalPop_State,
				 AgeO65Per_State = AgeO65_State/TotalPop_State)

Each_State <- Age.State

#################################################    Median Household Income    ##############################################################
# Median household income at Block Group level
Income.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B19013_001"), # Median Household Income in the Past 12 Months 
														keep_geo_vars = T) %>% 
  rename(MedHouseIncome_BG = B19013_001E) %>%
  rename(BG_ID_10 = GEOID) %>%
	select(BG_ID_10, MedHouseIncome_BG) %>%
  left_join(Each_State, by="BG_ID_10")

# Median household income at State level
Income.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B19013_001"), # Median Household Income in the Past 12 Months 
														keep_geo_vars = T) %>% 
  rename(MedHouseIncome_State = B19013_001E) %>%
  select(MedHouseIncome_State) %>%
  cbind(Income.BG)

Each_State <- Income.State

##############################################      Racial Breakdown     ###################################################################
# Racial Breakdown at Block Group level
Race.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B03002_003", # white alone
																					"B03002_004", # black or African American alone
																					"B03002_006", # Asian alone
																					"B03002_012", # Hispanic or Latino alone
																					"B03002_009"), # Two or more races
														keep_geo_vars = T) %>%
  rename(White_BG = B03002_003E,
				 Black_BG = B03002_004E,
				 Asian_BG = B03002_006E,
				 Hispanic_BG = B03002_012E,
				 TwoOrMore_BG = B03002_009E,
				 BG_ID_10 = GEOID) %>%
  select(BG_ID_10, White_BG, Black_BG, Asian_BG, Hispanic_BG, TwoOrMore_BG) %>%
  left_join(Each_State, Race.BG, by="BG_ID_10") %>%
  mutate(WhitePer_BG = White_BG/TotalPop_BG,
         BlackPer_BG = Black_BG/TotalPop_BG,
         AsianPer_BG = Asian_BG/TotalPop_BG,
         HispanicPer_BG = Hispanic_BG/TotalPop_BG,
         TwoOrMorePer_BG = TwoOrMore_BG/TotalPop_BG)

# Racial Breakdown at State level
Race.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B03002_003", # white alone
																					"B03002_004", # black or African American alone
																					"B03002_006", # Asian alone
																					"B03002_012", # Hispanic or Latino alone
																					"B03002_009"), # Two or more races
														keep_geo_vars = T) %>%
  rename(White_State = B03002_003E,
				 Black_State = B03002_004E,
				 Asian_State = B03002_006E,
				 Hispanic_State = B03002_012E,
				 TwoOrMore_State = B03002_009E) %>%
  select(White_State, Black_State, Asian_State, Hispanic_State, TwoOrMore_State) %>%
  cbind(Race.BG) %>%
  mutate(WhitePer_State = White_State/TotalPop_State,
				 BlackPer_State = Black_State/TotalPop_State,
				 AsianPer_State = Asian_State/TotalPop_State,
				 HispanicPer_State = Hispanic_State/TotalPop_State,
				 TwoOrMorePer_State = TwoOrMore_State/TotalPop_State)

Each_State <- Race.State

#####################################################    Gender Breakdown    ###############################################################
# Gender at Block Group level
Sex.BG <- tidycensus::get_acs(geography = "block group",
													 survey="acs5",
													 state=i,
													 year = endyr,
													 output = "wide",
													 variables = c("B01001_026", # Sex by Age - Female
													               "B01001_002"), # Sex by Age- Male
													 keep_geo_vars = T) %>%
  mutate(SexRatio_BG = B01001_026E/B01001_002E) %>%
  rename(Female_BG = B01001_026E,
				 Male_BG = B01001_002E,
				 BG_ID_10 = GEOID) %>%
	select(BG_ID_10, Female_BG, Male_BG, SexRatio_BG) %>%
  left_join(Each_State, Sex.BG, by="BG_ID_10") %>%
  mutate(FemalePer_BG = Female_BG/TotalPop_BG,
         MalePer_BG = Male_BG/TotalPop_BG)

# Gender at State level
Sex.State <- tidycensus::get_acs(geography = "state",
													 survey="acs5",
													 state=i,
													 year = endyr,
													 output = "wide",
													 variables = c("B01001_026", # Sex by Age - Female
													               "B01001_002"), # Sex by Age- Male
													 keep_geo_vars = T) %>% 
  mutate(SexRatio_State = B01001_026E/B01001_002E) %>%
  rename(Female_State = B01001_026E,
				 Male_State = B01001_002E) %>%
	select(Female_State, Male_State, SexRatio_State) %>%
  cbind(Sex.BG) %>%
  mutate(FemalePer_State = Female_State/TotalPop_State,
				 MalePer_State = Male_State/TotalPop_State)

Each_State <- Sex.State

#################################################    Average Household Size    ############################################################
# Average household size at Block Group level
HH.size.BG <- tidycensus::get_acs(geography = "block group",
															survey="acs5",
															state=i,
															year = endyr,
															output = "wide",
															variables = c("B11002_001", # Household type by relatives and nonrelatives for population in households
															              "B19001_001"), # Household income in the pas 12 months
															keep_geo_vars = T) %>%
  rename(BG_ID_10 = GEOID) %>%
  mutate(AveHouseH_BG = B11002_001E/B19001_001E) %>%
	select(BG_ID_10, AveHouseH_BG) %>%
  left_join(Each_State, HH.size.BG, by="BG_ID_10")

# Average household size at State level
HH.size.State <- tidycensus::get_acs(geography = "state",
															survey="acs5",
															state=i,
															year = endyr,
															output = "wide",
															variables = c("B11002_001", # Household type by relatives and nonrelatives for population in households
															              "B19001_001"), # Household income in the pas 12 months
															keep_geo_vars = T) %>%
  mutate(AveHouseH_State = B11002_001E/B19001_001E) %>%
	select(AveHouseH_State) %>%
  cbind(HH.size.BG) 

Each_State <- HH.size.State

#############################################   Educational Attainment    ##################################################################
# Educational Attainment at Block Group level
Educ.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B15002_001", # variables for Sex by Edu Attainment for Population 25 yrs or Over
																					"B15002_003","B15002_004","B15002_005",
																					"B15002_006","B15002_007","B15002_008","B15002_009","B15002_010",
																					"B15002_020","B15002_021","B15002_022","B15002_023","B15002_024",
																					"B15002_025","B15002_026","B15002_027",
																					"B15002_011","B15002_028",
																					"B15002_012","B15002_013","B15002_014",
																					"B15002_029","B15002_030","B15002_031",
																					"B15002_015","B15002_032",
																					"B15002_016","B15002_033",
																					"B15002_017","B15002_034",
																					"B15002_018","B15002_035"),keep_geo_vars = T) %>%
  rename(BG_ID_10 = GEOID) %>%
  mutate(LessThanHS_BG = (B15002_003E+B15002_004E+B15002_005E+B15002_006E+B15002_007E+B15002_008E+B15002_009E+B15002_010E+B15002_020E+B15002_021E+B15002_022E+B15002_023E+B15002_024E+B15002_025E+B15002_026E+B15002_027E),
				 HSGrad_BG = (B15002_011E + B15002_028E),
				 SomeColl_BG = (B15002_012E + B15002_013E + B15002_014E + B15002_029E + B15002_030E + B15002_031E),
				 Bach_BG = (B15002_015E + B15002_032E),
				 Master_BG = (B15002_016E + B15002_033E),
				 Prof_BG = (B15002_017E + B15002_034E),
				 Doc_BG = (B15002_018E + B15002_035E),
		    LessThanHSPer_BG = (B15002_003E+B15002_004E+B15002_005E+B15002_006E+B15002_007E+B15002_008E+B15002_009E+B15002_010E+B15002_020E+B15002_021E+B15002_022E+B15002_023E+B15002_024E+B15002_025E+B15002_026E+B15002_027E)/B15002_001E,
				 HSGradPer_BG = (B15002_011E + B15002_028E)/B15002_001E,
				 SomeCollPer_BG = (B15002_012E + B15002_013E + B15002_014E + B15002_029E + B15002_030E + B15002_031E)/B15002_001E,
				 BachPer_BG = (B15002_015E + B15002_032E)/B15002_001E,
				 MasterPer_BG = (B15002_016E + B15002_033E)/B15002_001E,
				 ProfPer_BG = (B15002_017E + B15002_034E)/B15002_001E,
				 DocPer_BG = (B15002_018E + B15002_035E)/B15002_001E) %>%
	select(BG_ID_10, LessThanHS_BG, HSGrad_BG, SomeColl_BG, Bach_BG, Master_BG, Prof_BG, Doc_BG,
	       LessThanHSPer_BG, HSGradPer_BG, SomeCollPer_BG, BachPer_BG, MasterPer_BG, ProfPer_BG, DocPer_BG) %>%
  left_join(Each_State, Educ.BG, by="BG_ID_10")

# Educational Attainment at State level
Educ.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B15002_001", # variables for Sex by Edu Attainment for Population 25 yrs or Over
																					"B15002_003","B15002_004","B15002_005",
																					"B15002_006","B15002_007","B15002_008","B15002_009","B15002_010",
																					"B15002_020","B15002_021","B15002_022","B15002_023","B15002_024",
																					"B15002_025","B15002_026","B15002_027",
																					"B15002_011","B15002_028",
																					"B15002_012","B15002_013","B15002_014",
																					"B15002_029","B15002_030","B15002_031",
																					"B15002_015","B15002_032",
																					"B15002_016","B15002_033",
																					"B15002_017","B15002_034",
																					"B15002_018","B15002_035"),keep_geo_vars = T) %>%
  mutate(LessThanHS_State = (B15002_003E+B15002_004E+B15002_005E+B15002_006E+B15002_007E+B15002_008E+B15002_009E+B15002_010E+B15002_020E+B15002_021E+B15002_022E+B15002_023E+B15002_024E+B15002_025E+B15002_026E+B15002_027E),
				 HSGrad_State = (B15002_011E + B15002_028E),
				 SomeColl_State = (B15002_012E + B15002_013E + B15002_014E + B15002_029E + B15002_030E + B15002_031E),
				 Bach_State = (B15002_015E + B15002_032E),
				 Master_State = (B15002_016E + B15002_033E),
				 Prof_State = (B15002_017E + B15002_034E),
				 Doc_State = (B15002_018E + B15002_035E),
		    LessThanHSPer_State = (B15002_003E+B15002_004E+B15002_005E+B15002_006E+B15002_007E+B15002_008E+B15002_009E+B15002_010E+B15002_020E+B15002_021E+B15002_022E+B15002_023E+B15002_024E+B15002_025E+B15002_026E+B15002_027E)/B15002_001E,
				 HSGradPer_State = (B15002_011E + B15002_028E)/B15002_001E,
				 SomeCollPer_State = (B15002_012E + B15002_013E + B15002_014E + B15002_029E + B15002_030E + B15002_031E)/B15002_001E,
				 BachPer_State = (B15002_015E + B15002_032E)/B15002_001E,
				 MasterPer_State = (B15002_016E + B15002_033E)/B15002_001E,
				 ProfPer_State = (B15002_017E + B15002_034E)/B15002_001E,
				 DocPer_State = (B15002_018E + B15002_035E)/B15002_001E) %>%
	select(LessThanHS_State, HSGrad_State, SomeColl_State, Bach_State, Master_State, Prof_State, Doc_State,
	       LessThanHSPer_State, HSGradPer_State, SomeCollPer_State, BachPer_State, MasterPer_State, ProfPer_State, DocPer_State) %>%
  cbind(Educ.BG) 

Each_State <- Educ.State

##########################################      Single Parent Households     ##################################################################
# Single parent households at Block Group level
Single.HH.BG <- tidycensus::get_acs(geography = "block group",
															survey="acs5",
															state=i,
															year = endyr,
															output = "wide",
															variables = c("B11001_006", # Female Hoseholder, No Husband Present
																						"B11001_005", # Male Householder, No Wife Present
																						"B11001_001"), # Total number of households
															keep_geo_vars = T) %>% 
  rename(BG_ID_10 = GEOID) %>%
  mutate(FemHeadPer_BG = B11001_006E/B11001_001E,
	       MaleHeadPer_BG = B11001_005E/B11001_001E) %>%
	select(BG_ID_10, FemHeadPer_BG, MaleHeadPer_BG) %>%
  left_join(Each_State, Single.HH.BG, by="BG_ID_10")

# Single parent households at State level
Single.HH.State <- tidycensus::get_acs(geography = "state",
															survey="acs5",
															state=i,
															year = endyr,
															output = "wide",
															variables = c("B11001_006", # Female Hoseholder, No Husband Present
																						"B11001_005", # Male Householder, No Wife Present
																						"B11001_001"), # Total number of households
															keep_geo_vars = T) %>% 
  mutate(FemHeadPer_State = B11001_006E/B11001_001E,
	       MaleHeadPer_State = B11001_005E/B11001_001E) %>%
	select(FemHeadPer_State, MaleHeadPer_State) %>%
  cbind(Single.HH.BG) 

Each_State <- Single.HH.State

###########################################      Population in Poverty    ######################################################################
# Population in poverty at Block Group level
Poverty.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B17010_002", # Income in the Past 12 Months Below Poverty Level (Family households in poverty)
																					"B17010_001",  # Total Families Below Poverty Level
																					"B17001_002", # Persons below poverty
																					"B17001_001"), # Total
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(FamPovPer_BG = B17010_002E/B17010_001E,
	       PopPovPer_BG = B17001_002E/B17001_001E,
	       TotalPopPov_BG = B17001_002E) %>%
	select(BG_ID_10, FamPovPer_BG, PopPovPer_BG, TotalPopPov_BG) %>%
  left_join(Each_State, Poverty.BG, by="BG_ID_10")

# Population in poverty at State level
Poverty.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B17010_002", # Income in the Past 12 Months Below Poverty Level
																					"B17010_001", # Total Families Below Poverty Level
																					"B17001_002", # Persons below poverty
																					"B17001_001"), # Total 
														keep_geo_vars = T) %>%
	mutate(FamPovPer_State = B17010_002E/B17010_001E,
	       PopPovPer_State = B17001_002E/B17001_001E,
	       TotalPopPov_State = B17001_002E) %>%
	select(FamPovPer_State, PopPovPer_State, TotalPopPov_State)  %>%
  cbind(Poverty.BG) 

Each_State <- Poverty.State

########################################     Elderly People Living Alone    ##############################################################
######## GIVE US NA VALUES FOR BLOCK GROUP LEVEL FOR ALL STATES #######

# Elderly People Living Alone at Block Group level
OldAlone.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B11010_005", # Male householder, Living alone, 65 years and over
																					"B11010_012", # Female householder, Living alone, 65 years and over
																					"B11010_001"), # Total
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(OldAlonePer_BG = (B11010_012E + B11010_005E)/B11010_001E) %>%
	select(BG_ID_10, OldAlonePer_BG) 
# OldAlone.BG
  
# Elderly People Living Alone at State level
OldAlone.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B11010_005", # Male householder, Living alone, 65 years and over
																					"B11010_012", # Female householder, Living alone, 65 years and over
																					"B11010_001"), # Total
														keep_geo_vars = T) %>%
	mutate(OldAlonePer_State = (B11010_012E + B11010_005E)/B11010_001E) %>%
	select(OldAlonePer_State) 

Each_State <- OldAlone.State %>%
  cbind(Each_State)

                                             # ----------------------------- #
                                             #    Educational Institutions   #
                                             #-------------------------------#

# ## Number/Type of Schools (https://nces.ed.gov/)

####################################################    Number/Type of Schools   ################################################
## Number/Type of Schools 
# Public School Districts:
MA.Num.Schools.District <- 432
ME.Num.Schools.District <- 276
CT.Num.Schools.District <- 204
RI.Num.Schools.District <- 64
NH.Num.Schools.District <- 308
VT.Num.Schools.District <- 235

# Public Schools:
MA.Num.PubSchools <- 1853
ME.Num.PubSchools <- 599
CT.Num.PubSchools <- 1028
RI.Num.PubSchools <- 320
NH.Num.PubSchools <- 494
VT.Num.PubSchools <- 312

# Private Schools:
MA.Num.PrvSchools <- 517
ME.Num.PrvSchools <- 118
CT.Num.PrvSchools <- 261
RI.Num.PrvSchools <- 84
NH.Num.PrvSchools <- 175
VT.Num.PrvSchools <- 83

# Number of PK-12 Enrollment at block group level
Enrol.Sch.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B14001_003", # Enrolled in preschool
																					"B14001_004", # Enrolled in kindergarten
																					"B14001_005", # Enrolled in grade 1 to 4
																					"B14001_006", # Enrolled in grade 5 to 8
																					"B14001_007"), # Enrolled in grade 9 to 12
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(EnrolPK12_BG = B14001_003E + B14001_004E + B14001_005E + B14001_006E + B14001_007E) %>%
	select(BG_ID_10, EnrolPK12_BG) %>%
  left_join(Each_State, Enrol.Sch.BG, by="BG_ID_10")

# Number of PK-12 Enrollment at state level
Enrol.Sch.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B14001_003", # Enrolled in preschool
																					"B14001_004", # Enrolled in kindergarten
																					"B14001_005", # Enrolled in grade 1 to 4
																					"B14001_006", # Enrolled in grade 5 to 8
																					"B14001_007"), # Enrolled in grade 9 to 12
														keep_geo_vars = T) %>%
	mutate(EnrolPK12_State = B14001_003E + B14001_004E + B14001_005E + B14001_006E + B14001_007E) %>%
	select(EnrolPK12_State) %>%
  cbind(Enrol.Sch.BG) 

Each_State <- Enrol.Sch.State

####################################################      Number/Type of Universities     ################################################
## Number/Type of Universities (https://nces.ed.gov/)
# Number of institutions: (level of certificate, bachlor, associate, advanced)
MA.Num.Uni <- 151
ME.Num.Uni <- 36
CT.Num.Uni <- 67
RI.Num.Uni <- 22
NH.Num.Uni <- 37
VT.Num.Uni <- 21

########################################################################################################################################

                                                #----------------------#
                                                #       EMPLOYMENT     #
                                                #----------------------#


##########################################    Number of Jobs within Community Boundaries   #############################################
# Number of Jobs within Community Boundaries at Block Group level
# Should change for city level
Num.jobs.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = "B08007_002", # Total worked in state of residence
														              keep_geo_vars = T) %>%
  rename(BG_ID_10 = GEOID) %>%
	mutate(NumJobs_BG = B08007_002E) %>%
	select(BG_ID_10, NumJobs_BG) %>%
  left_join(Each_State, Num.jobs.BG, by="BG_ID_10")

# Number of Jobs within Community Boundaries at State level
Num.jobs.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = "B08007_002", # Total worked in state of residence
														              keep_geo_vars = T) %>%
	mutate(NumJobs_State = B08007_002E) %>%
	select(NumJobs_State) %>%
  cbind(Num.jobs.BG) 

Each_State <- Num.jobs.State

# Work place at Block Group level
Place.Work.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B08007_003", # Worked in state of residence and worked in county of residence
														              "B08007_001", # Total
														              "B08008_003", # Worked in place of residence
														              "B08008_001"), # Total 
														              keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(WorkStateCounty_BG = B08007_003E,
	       WorkStateCountyPer_BG = B08007_003E/B08007_001E,
	       WorkPlace_BG = B08008_003E,
	       WorkPlacePer_BG = B08008_003E/B08008_001E) %>%
	select(BG_ID_10, WorkStateCounty_BG, WorkStateCountyPer_BG, WorkPlace_BG, WorkPlacePer_BG) %>%
  left_join(Each_State, Place.Work.BG, by="BG_ID_10")

# Work place at State level
Place.Work.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B08007_003", # Worked in state of residence and worked in county of residence
														              "B08007_001", # Total
														              "B08008_003", # Worked in place of residence
														              "B08008_001"), # Total 
														              keep_geo_vars = T) %>%
	mutate(WorkStateCounty_State = B08007_003E,
	       WorkStateCountyPer_State = B08007_003E/B08007_001E,
	       WorkPlace_State = B08008_003E,
	       WorkPlacePer_State = B08008_003E/B08008_001E) %>%
	select(WorkStateCounty_State, WorkStateCountyPer_State, WorkPlace_State, WorkPlacePer_State) %>%
  cbind(Place.Work.BG) 

Each_State <- Place.Work.State

############################################# Labor Force (Total number, participation)  ####################################
# Number of labor force at Block Group level
Labor.Force.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B23025_002", # Number of Labor Force 16 years and over
														              "B23025_003", # Number of Civilian Labor Force 16 years and over
														              "B23025_006", # Number of Armed Forces 16 years and over
														              "B23025_001"), # Total
														              keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(LabForce_BG = B23025_002E,
	       LabForcePer_BG = B23025_002E/B23025_001E,
	       CivLabForce_BG = B23025_003E,
	       CivLabForcePer_BG = B23025_003E/B23025_001E,
	       Military_BG = B23025_006E,
	       MilitaryPer_BG = 	B23025_006E/B23025_001E,
	       TotalWorkers_BG = B23025_001E) %>%
	select(BG_ID_10, LabForce_BG, LabForcePer_BG, CivLabForce_BG, CivLabForcePer_BG, Military_BG, MilitaryPer_BG, TotalWorkers_BG) %>%
  left_join(Each_State, Labor.Force.BG, by="BG_ID_10")

# Number of labor force at State level
Labor.Force.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B23025_002", # Number of Labor Force 16 years and over (civilian + armed)
														              "B23025_003", # Number of Civilian Labor Force 16 years and over
														              "B23025_006", # Number of Armed Forces 16 years and over
														              "B23025_001"), # Total
														              keep_geo_vars = T) %>%
	mutate(LabForce_State = B23025_002E,
	       LabForcePer_State = B23025_002E/B23025_001E,
	       CivLabForce_State = B23025_003E,
	       CivLabForcePer_State = B23025_003E/B23025_001E,
	       Military_State = B23025_006E,
	       MilitaryPer_State = 	B23025_006E/B23025_001E,
	       TotalWorkers_State = B23025_001E) %>%
	select(LabForce_State, LabForcePer_State, CivLabForce_State, CivLabForcePer_State, Military_State, MilitaryPer_State, TotalWorkers_State) %>%
  cbind(Labor.Force.BG) 

Each_State <- Labor.Force.State

#####################################################    Employed and Unemployed   ####################################
# Employed and Unemployed cases at Block Group level
Emp.Unemp.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B23025_003", # Number of civilian Labor Force 16 years and over
														              "B23025_004", # Number of Employed individuals 16 years and over
														              "B23025_005"), # Number of Unemployed individuals 16 years and over
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(EmpRate_BG = B23025_004E/B23025_003E,
	       UnempRate_BG = B23025_005E/B23025_003E,
	       EmployedCLF_BG = B23025_004E,
	       UnemployedCLF_BG = B23025_005E) %>%
	select(BG_ID_10 ,EmpRate_BG, UnempRate_BG, EmployedCLF_BG, UnemployedCLF_BG) %>%
  left_join(Each_State, Emp.Unemp.BG, by="BG_ID_10")

# Employed and Unemployed cases at State level
Emp.Unemp.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B23025_003", # Number of civilian Labor Force 16 years and over
														              "B23025_004", # Number of Employed individuals 16 years and over
														              "B23025_005"), # Number of Unemployed individuals 16 years and over
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(EmpRate_State = B23025_004E/B23025_003E,
	       UnempRate_State = B23025_005E/B23025_003E,
	       EmployedCLF_State = B23025_004E,
	       UnemployedCLF_State = B23025_005E) %>%
	select(EmpRate_State, UnempRate_State, EmployedCLF_State, UnemployedCLF_State) %>%
  cbind(Emp.Unemp.BG) 

Each_State <- Emp.Unemp.State

################################    Major Employers by NCAIS Code    ##########################################
# Major Employers by NCAIS Code at Block Group level
Emp.NCAIS.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("C24030_002", # Number of male by industry for the civilian employed, 16 years and over
														              "C24030_029", # Number of female by industry for the civilian employed, 16 years and over
														              "C24030_001"), # Total
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(MaleNCAIS_BG = C24030_002E,
	       FemaleNCAIS_BG = C24030_029E,
	       MaleNCAISPer_BG = C24030_002E/C24030_001E,
	       FemaleNCAISPer_BG = C24030_029E/C24030_001E) %>%
	select(BG_ID_10 , MaleNCAIS_BG, FemaleNCAIS_BG, MaleNCAISPer_BG, FemaleNCAISPer_BG) %>%
  left_join(Each_State, Emp.NCAIS.BG, by="BG_ID_10")

# Major Employers by NCAIS Code at State level
Emp.NCAIS.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("C24030_002", # Number of male by industry for the civilian employed, 16 years and over
														              "C24030_029", # Number of female by industry for the civilian employed, 16 years and over
														              "C24030_001"), # Total
														keep_geo_vars = T) %>%
	mutate(MaleNCAIS_State = C24030_002E,
	       FemaleNCAIS_State = C24030_029E,
	       MaleNCAISPer_State = C24030_002E/C24030_001E,
	       FemaleNCAISPer_State = C24030_029E/C24030_001E) %>%
	select(MaleNCAIS_State, FemaleNCAIS_State, MaleNCAISPer_State, FemaleNCAISPer_State) %>%
  cbind(Emp.NCAIS.BG) 

Each_State <- Emp.NCAIS.State

######################################    Top Industries by NCAIS Code   ##################################################

# Top Industries by NCAIS Code at Block Group level
Industries.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("C24030_003", # Agriculture, forestry, fishing and hunting, and mining (Male)
														              "C24030_030", # Agriculture, forestry, fishing and hunting, and mining (Female)
														              "C24030_006", # Construction (Male)
														              "C24030_033", # Construction (Female)
														              "C24030_007", # Manufacturing (Male)
														              "C24030_034", # Manufacturing (Female)
														              "C24030_008", # Wholesale trade (Male)
														              "C24030_035", # Wholesale trade (Female)
														              "C24030_009", # Retail trade (Male)
														              "C24030_036", # Retail trade (Female)
														              "C24030_010", # Transportation and warehousing, and utilities (Male)
														              "C24030_037", # Transportation and warehousing, and utilities (Female)
														              "C24030_013", # Information (Male)
														              "C24030_040", # Information (Female)
														              "C24030_014", # Finance and insurance, and real estate, and rental and leasing (Male)
														              "C24030_041", # Finance and insurance, and real estate, and rental and leasing (Female)
														              "C24030_017", # Professional, scientific, and management, and administrative, and waste management services (Male)
														              "C24030_044", # Professional, scientific, and management, and administrative, and waste management services (Female)
														              "C24030_021", # Educational services, and health care and social assistance (Male)
														              "C24030_048", # Educational services, and health care and social assistance (Female)
														              "C24030_024", # Arts, entertainment, and recreation, and accommodation and food services (Male)
														              "C24030_051", # Arts, entertainment, and recreation, and accommodation and food services (Female)
														              "C24030_027", # Other services, except public administration (Male)
														              "C24030_054", # Other services, except public administration (Female)
														              "C24030_028", # Public administration (Male)
														              "C24030_055", # Public administration (Female)
														              "C24030_001"), # Total
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(Agriculture_BG = (C24030_003E + C24030_030E)/C24030_001E,
	       Construction_BG = (C24030_006E + C24030_033E)/C24030_001E,
	       Manufacturing_BG = (C24030_007E + C24030_034E)/C24030_001E,
	       WholesaleTrade_BG = (C24030_008E + C24030_035E)/C24030_001E,
	       RetailTrade_BG = (C24030_009E + C24030_036E)/C24030_001E,
	       Transportation_BG = (C24030_010E + C24030_037E)/C24030_001E,
	       Information_BG = (C24030_013E + C24030_040E)/C24030_001E,
	       Finance_Ins_BG = (C24030_014E + C24030_041E)/C24030_001E,
	       Professional_BG = (C24030_017E + C24030_044E)/C24030_001E,
	       Educ_Health_SocSvcs_BG = (C24030_021E + C24030_048E)/C24030_001E,
	       RecreationEtc_BG = (C24030_024E + C24030_051E)/C24030_001E,
	       OtherIndustries_BG = (C24030_027E + C24030_054E)/C24030_001E,
	       PublicAdmin_BG = (C24030_028E + C24030_055E)/C24030_001E) %>%
	select(BG_ID_10,Agriculture_BG,Construction_BG,Manufacturing_BG,WholesaleTrade_BG,RetailTrade_BG,Transportation_BG,Information_BG,
	       Finance_Ins_BG,Professional_BG,Educ_Health_SocSvcs_BG,RecreationEtc_BG,OtherIndustries_BG,PublicAdmin_BG) %>%
  left_join(Each_State, Industries.BG, by="BG_ID_10")

# Top Industries by NCAIS Code at State level
Industries.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("C24030_003", # Agriculture, forestry, fishing and hunting, and mining (Male)
														              "C24030_030", # Agriculture, forestry, fishing and hunting, and mining (Female)
														              "C24030_006", # Construction (Male)
														              "C24030_033", # Construction (Female)
														              "C24030_007", # Manufacturing (Male)
														              "C24030_034", # Manufacturing (Female)
														              "C24030_008", # Wholesale trade (Male)
														              "C24030_035", # Wholesale trade (Female)
														              "C24030_009", # Retail trade (Male)
														              "C24030_036", # Retail trade (Female)
														              "C24030_010", # Transportation and warehousing, and utilities (Male)
														              "C24030_037", # Transportation and warehousing, and utilities (Female)
														              "C24030_013", # Information (Male)
														              "C24030_040", # Information (Female)
														              "C24030_014", # Finance and insurance, and real estate, and rental and leasing (Male)
														              "C24030_041", # Finance and insurance, and real estate, and rental and leasing (Female)
														              "C24030_017", # Professional, scientific, and management, and administrative, and waste management services (Male)
														              "C24030_044", # Professional, scientific, and management, and administrative, and waste management services (Female)
														              "C24030_021", # Educational services, and health care and social assistance (Male)
														              "C24030_048", # Educational services, and health care and social assistance (Female)
														              "C24030_024", # Arts, entertainment, and recreation, and accommodation and food services (Male)
														              "C24030_051", # Arts, entertainment, and recreation, and accommodation and food services (Female)
														              "C24030_027", # Other services, except public administration (Male)
														              "C24030_054", # Other services, except public administration (Female)
														              "C24030_028", # Public administration (Male)
														              "C24030_055", # Public administration (Female)
														              "C24030_001"), # Total
														keep_geo_vars = T) %>%
	mutate(Agriculture_State = (C24030_003E + C24030_030E)/C24030_001E,
	       Construction_State = (C24030_006E + C24030_033E)/C24030_001E,
	       Manufacturing_State = (C24030_007E + C24030_034E)/C24030_001E,
	       WholesaleTrade_State = (C24030_008E + C24030_035E)/C24030_001E,
	       RetailTrade_State = (C24030_009E + C24030_036E)/C24030_001E,
	       Transportation_State = (C24030_010E + C24030_037E)/C24030_001E,
	       Information_State = (C24030_013E + C24030_040E)/C24030_001E,
	       Finance_Ins_State = (C24030_014E + C24030_041E)/C24030_001E,
	       Professional_State = (C24030_017E + C24030_044E)/C24030_001E,
	       Educ_Health_SocSvcs_State = (C24030_021E + C24030_048E)/C24030_001E,
	       RecreationEtc_State = (C24030_024E + C24030_051E)/C24030_001E,
	       OtherIndustries_State = (C24030_027E + C24030_054E)/C24030_001E,
	       PublicAdmin_State = (C24030_028E + C24030_055E)/C24030_001E) %>%
	select(Agriculture_State,Construction_State,Manufacturing_State,WholesaleTrade_State,RetailTrade_State,Transportation_State,Information_State,
	       Finance_Ins_State,Professional_State,Educ_Health_SocSvcs_State,RecreationEtc_State,OtherIndustries_State,PublicAdmin_State) %>%
  cbind(Industries.BG) 

Each_State <- Industries.State

###########################    Earning Breakdown   ####################################

# Earning at Block Group level
Med.Earning.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = "B20017_001", # Median earnings in the past 12 months 
	keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(MedEarning_BG = B20017_001E) %>%
	select(BG_ID_10 ,MedEarning_BG) %>%
  left_join(Each_State, Med.Earning.BG, by="BG_ID_10")

# Earning at State level
Med.Earning.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = "B20017_001", # Median earnings in the past 12 months 
	keep_geo_vars = T) %>%
	mutate(MedEarning_State = B20017_001E) %>%
	select(MedEarning_State) %>%
  cbind(Med.Earning.BG) 

Each_State <- Med.Earning.State

#############################################    Employee Age   #############################################################
# Method 1:

### Number of labor force = (Civilian + Armed)
### Number of civilian = (employed + unemployed)
### Therefore => workers = (civilian(employed) + Armed)

# Age of employees at Block Group level
Emp.Age.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide", # Age by employment status for the population 16 years and over (Employed+Armed)
						     variables = c("B23001_005","B23001_007","B23001_012","B23001_014","B23001_019","B23001_021","B23001_026","B23001_028", # Age 29 or younger male
								"B23001_033","B23001_035","B23001_040","B23001_042","B23001_047","B23001_049", # Age 30 to 54 male
								"B23001_054","B23001_056","B23001_061","B23001_063","B23001_068","B23001_070","B23001_075","B23001_080","B23001_085", # Age 55 or older male
								"B23001_091","B23001_093","B23001_098","B23001_100","B23001_105","B23001_107","B23001_112","B23001_114", # Age 29 or younger female
								"B23001_119","B23001_121","B23001_126","B23001_128","B23001_133","B23001_135", # Age 30 to 54 female
								"B23001_140","B23001_142","B23001_147","B23001_149","B23001_154","B23001_156","B23001_161","B23001_166","B23001_171", # Age 55 or older female
														              "B23001_001"), # Total
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(AgeEmpU29_BG = B23001_005E+B23001_007E+B23001_012E+B23001_014E+B23001_019E+B23001_021E+B23001_026E+B23001_028E+
	         B23001_091E+B23001_093E+B23001_098E+B23001_100E+B23001_105E+B23001_107E+B23001_112E+B23001_114E,
	       AgeEmp3054_BG = B23001_033E+B23001_035E+	B23001_040E+B23001_042E+B23001_047E+B23001_049E+
	         B23001_119E+B23001_121E+B23001_126E+B23001_128E+B23001_133E+B23001_135E,
	       AgeEmpO55_BG = B23001_054E+B23001_056E+B23001_061E+B23001_063E+B23001_068E+B23001_070E+B23001_075E+B23001_080E+B23001_085E+
	        B23001_140E+B23001_142E+B23001_147E+B23001_149E+B23001_154E+B23001_156E+B23001_161E+B23001_166E+B23001_171E,
	       
	       AgeEmpU29Per_BG = (B23001_005E+B23001_007E+B23001_012E+B23001_014E+B23001_019E+B23001_021E+B23001_026E+B23001_028E+
	         B23001_091E+B23001_093E+B23001_098E+B23001_100E+B23001_105E+B23001_107E+B23001_112E+B23001_114E)/B23001_001E,
	        AgeEmp3054Per_BG = (B23001_033E+B23001_035E+B23001_040E+B23001_042E+B23001_047E+B23001_049E+
	         B23001_119E+B23001_121E+B23001_126E+B23001_128E+B23001_133E+B23001_135E)/B23001_001E,
	       AgeEmpO55Per_BG = (B23001_054E+B23001_056E+B23001_061E+B23001_063E+B23001_068E+B23001_070E+B23001_075E+B23001_080E+B23001_085E+
	        B23001_140E+B23001_142E+B23001_147E+B23001_149E+B23001_154E+B23001_156E+B23001_161E+B23001_166E+B23001_171E)/B23001_001E) %>%
	select(BG_ID_10,AgeEmpU29_BG,AgeEmp3054_BG,AgeEmpO55_BG,AgeEmpU29Per_BG,AgeEmp3054Per_BG,AgeEmpO55Per_BG) %>%
  left_join(Each_State, Emp.Age.BG, by="BG_ID_10")

# Age of employees at State level
Emp.Age.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide", # Age by employment status for the population 16 years and over (Employed+Armed)
						     variables = c("B23001_005","B23001_007","B23001_012","B23001_014","B23001_019","B23001_021","B23001_026","B23001_028", # Age 29 or younger male
								"B23001_033","B23001_035","B23001_040","B23001_042","B23001_047","B23001_049", # Age 30 to 54 male
								"B23001_054","B23001_056","B23001_061","B23001_063","B23001_068","B23001_070","B23001_075","B23001_080","B23001_085", # Age 55 or older male
								"B23001_091","B23001_093","B23001_098","B23001_100","B23001_105","B23001_107","B23001_112","B23001_114", # Age 29 or younger female
								"B23001_119","B23001_121","B23001_126","B23001_128","B23001_133","B23001_135", # Age 30 to 54 female
								"B23001_140","B23001_142","B23001_147","B23001_149","B23001_154","B23001_156","B23001_161","B23001_166","B23001_171", # Age 55 or older female
														              "B23001_001"), # Total
														keep_geo_vars = T) %>%
	mutate(AgeEmpU29_State = B23001_005E+B23001_007E+B23001_012E+B23001_014E+B23001_019E+B23001_021E+B23001_026E+B23001_028E+
	         B23001_091E+B23001_093E+B23001_098E+B23001_100E+B23001_105E+B23001_107E+B23001_112E+B23001_114E,
	       AgeEmp3054_State = B23001_033E+B23001_035E+	B23001_040E+B23001_042E+B23001_047E+B23001_049E+
	         B23001_119E+B23001_121E+B23001_126E+B23001_128E+B23001_133E+B23001_135E,
	       AgeEmpO55_State = B23001_054E+B23001_056E+B23001_061E+B23001_063E+B23001_068E+B23001_070E+B23001_075E+B23001_080E+B23001_085E+
	        B23001_140E+B23001_142E+B23001_147E+B23001_149E+B23001_154E+B23001_156E+B23001_161E+B23001_166E+B23001_171E,
	       
	       AgeEmpU29Per_State = (B23001_005E+B23001_007E+B23001_012E+B23001_014E+B23001_019E+B23001_021E+B23001_026E+B23001_028E+
	         B23001_091E+B23001_093E+B23001_098E+B23001_100E+B23001_105E+B23001_107E+B23001_112E+B23001_114E)/B23001_001E,
	        AgeEmp3054Per_State = (B23001_033E+B23001_035E+B23001_040E+B23001_042E+B23001_047E+B23001_049E+
	         B23001_119E+B23001_121E+B23001_126E+B23001_128E+B23001_133E+B23001_135E)/B23001_001E,
	       AgeEmpO55Per_State = (B23001_054E+B23001_056E+B23001_061E+B23001_063E+B23001_068E+B23001_070E+B23001_075E+B23001_080E+B23001_085E+
	        B23001_140E+B23001_142E+B23001_147E+B23001_149E+B23001_154E+B23001_156E+B23001_161E+B23001_166E+B23001_171E)/B23001_001E) %>%
	select(AgeEmpU29_State,AgeEmp3054_State,AgeEmpO55_State,AgeEmpU29Per_State,AgeEmp3054Per_State,AgeEmpO55Per_State) %>%
  cbind(Emp.Age.BG) 

Each_State <- Emp.Age.State

# Method 2:
# Number of labor force = (Civilian + Armed) at Block Group level
Emp.Age.BG.Labors <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B23001_004", "B23001_011","B23001_017","B23001_025",
														              "B23001_032","B23001_039","B23001_046","B23001_053","B23001_060",
														              "B23001_067","B23001_074","B23001_079","B23001_084",
														              "B23001_089","B23001_096","B23001_104","B23001_111","B23001_118","B23001_125",
														              "B23001_132","B23001_139","B23001_146","B23001_153","B23001_160","B23001_165","B23001_170",
														              "B23001_001"),
														keep_geo_vars = T) %>%
  	rename(BG_ID_10 = GEOID) %>%
	mutate(AgeEmpU29_BG_Labors = B23001_004E+B23001_011E+B23001_017E+B23001_025E+B23001_089E+B23001_096E+B23001_104E+B23001_111E,
	       AgeEmp3054_BG_Labors = B23001_032E+B23001_039E+B23001_046E+B23001_118E+B23001_125E+B23001_132E,
	       AgeEmpO55_BG_Labors = B23001_053E+B23001_060E+B23001_067E+B23001_074E+B23001_079E+B23001_084E+	B23001_139E+B23001_146E+B23001_153E+B23001_160E+B23001_165E+B23001_170E,
	       
	       AgeEmpU29Per_BG_Labors = (B23001_004E+B23001_011E+B23001_017E+B23001_025E+B23001_089E+B23001_096E+B23001_104E+B23001_111E)/B23001_001E,
	       AgeEmp3054Per_BG_Labors = (B23001_032E+B23001_039E+B23001_046E+B23001_118E+B23001_125E+B23001_132E)/B23001_001E,
	       AgeEmpO55Per_BG_Labors = (B23001_053E+B23001_060E+B23001_067E+B23001_074E+B23001_079E+B23001_084E+	B23001_139E+B23001_146E+B23001_153E+B23001_160E+B23001_165E+B23001_170E)/B23001_001E) %>%
	select(BG_ID_10, AgeEmpU29_BG_Labors, AgeEmp3054_BG_Labors, AgeEmpO55_BG_Labors, 
	       AgeEmpU29Per_BG_Labors, AgeEmp3054Per_BG_Labors, AgeEmpO55Per_BG_Labors) %>%
  left_join(Each_State, Emp.Age.BG.Labors, by="BG_ID_10")

# Number of labor force = (Civilian + Armed) at State level
Emp.Age.State.Labors <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state="ME",
														year = endyr,
														output = "wide",
														variables = c("B23001_004", "B23001_011","B23001_017","B23001_025",
														              "B23001_032","B23001_039","B23001_046","B23001_053","B23001_060",
														              "B23001_067","B23001_074","B23001_079","B23001_084",
														              "B23001_089","B23001_096","B23001_104","B23001_111","B23001_118","B23001_125",
														              "B23001_132","B23001_139","B23001_146","B23001_153","B23001_160","B23001_165","B23001_170",
														              "B23001_001"),
														keep_geo_vars = T) %>%
	mutate(AgeEmpU29_State_Labors = B23001_004E+B23001_011E+B23001_017E+B23001_025E+B23001_089E+B23001_096E+B23001_104E+B23001_111E,
	       AgeEmp3054_State_Labors = B23001_032E+B23001_039E+B23001_046E+B23001_118E+B23001_125E+B23001_132E,
	       AgeEmpO55_State_Labors = B23001_053E+B23001_060E+B23001_067E+B23001_074E+B23001_079E+B23001_084E+	B23001_139E+B23001_146E+B23001_153E+B23001_160E+B23001_165E+B23001_170E,
	       
	       AgeEmpU29Per_State_Labors = (B23001_004E+B23001_011E+B23001_017E+B23001_025E+B23001_089E+B23001_096E+B23001_104E+B23001_111E)/B23001_001E,
	       AgeEmp3054Per_State_Labors = (B23001_032E+B23001_039E+B23001_046E+B23001_118E+B23001_125E+B23001_132E)/B23001_001E,
	       AgeEmpO55Per_State_Labors = (B23001_053E+B23001_060E+B23001_067E+B23001_074E+B23001_079E+B23001_084E+	B23001_139E+B23001_146E+B23001_153E+B23001_160E+B23001_165E+B23001_170E)/B23001_001E) %>%
	select(AgeEmpU29_State_Labors, AgeEmp3054_State_Labors, AgeEmpO55_State_Labors,
	       AgeEmpU29Per_State_Labors, AgeEmp3054Per_State_Labors, AgeEmpO55Per_State_Labors) %>%
  cbind(Emp.Age.BG.Labors) 

Each_State <- Emp.Age.State.Labors



#############################################      Employee Race    ############################################################
# Employee race at Block Group level
Emp.Race.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("C23002A_007","C23002A_012","C23002A_020","C23002A_025","C23002A_005","C23002A_018", # White alone
														              "C23002B_007","C23002B_012","C23002B_020","C23002B_025","C23002B_005","C23002B_018", # Black or African American alone
														              "C23002D_007","C23002D_012","C23002D_020","C23002D_025","C23002D_005","C23002D_018", # Asian alone
														              "C23002I_007","C23002I_012","C23002I_020","C23002I_025","C23002I_005","C23002I_018", # Hispanic or Latino alone
														              "C23002G_007","C23002G_012","C23002G_020","C23002G_025","C23002G_005","C23002G_018",# Two or more races
														              "B23001_001"), # Total

						keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(WhiteEmp_BG = C23002A_007E+C23002A_012E+C23002A_020E+C23002A_025E+C23002A_005E+C23002A_018E,
	       BlackEmp_BG = C23002B_007E+C23002B_012E+C23002B_020E+C23002B_025E+C23002B_005E+C23002B_018E,
	       AsianEmp_BG = C23002D_007E+C23002D_012E+C23002D_020E+C23002D_025E+C23002D_005E+C23002D_018E,
	       HispanicEmp_BG = C23002I_007E+C23002I_012E+C23002I_020E+C23002I_025E+C23002I_005E+C23002I_018E,
	       TwoOrMoreEmp_BG = C23002G_007E+C23002G_012E+C23002G_020E+C23002G_025E+C23002G_005E+C23002G_018E,
         WhiteEmpPer_BG = (C23002A_007E+C23002A_012E+C23002A_020E+C23002A_025E+C23002A_005E+C23002A_018E)/B23001_001E,
	       BlackEmpPer_BG = (C23002B_007E+C23002B_012E+C23002B_020E+C23002B_025E+C23002B_005E+C23002B_018E)/B23001_001E,
	       AsianEmpPer_BG = (C23002D_007E+C23002D_012E+C23002D_020E+C23002D_025E+C23002D_005E+C23002D_018E)/B23001_001E,
	       HispanicEmpPer_BG = (C23002I_007E+C23002I_012E+C23002I_020E+C23002I_025E+C23002I_005E+C23002I_018E)/B23001_001E,
	       TwoOrMoreEmpPer_BG = (C23002G_007E+C23002G_012E+C23002G_020E+C23002G_025E+C23002G_005E+C23002G_018E)/B23001_001E) %>%
	select(BG_ID_10 ,WhiteEmp_BG, BlackEmp_BG, AsianEmp_BG, HispanicEmp_BG, TwoOrMoreEmp_BG,
	       WhiteEmpPer_BG, BlackEmpPer_BG, AsianEmpPer_BG, HispanicEmpPer_BG, TwoOrMoreEmpPer_BG) %>%
  left_join(Each_State, Emp.Race.BG, by="BG_ID_10")

# Employee race at State level
Emp.Race.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("C23002A_007","C23002A_012","C23002A_020","C23002A_025","C23002A_005","C23002A_018", # White alone
														              "C23002B_007","C23002B_012","C23002B_020","C23002B_025","C23002B_005","C23002B_018", # Black or African American alone
														              "C23002D_007","C23002D_012","C23002D_020","C23002D_025","C23002D_005","C23002D_018", # Asian alone
														              "C23002I_007","C23002I_012","C23002I_020","C23002I_025","C23002I_005","C23002I_018", # Hispanic or Latino alone
														              "C23002G_007","C23002G_012","C23002G_020","C23002G_025","C23002G_005","C23002G_018", # Two or more races
														              "B23001_001"), # Total
														keep_geo_vars = T) %>%
	mutate(WhiteEmp_State = C23002A_007E+C23002A_012E+C23002A_020E+C23002A_025E+C23002A_005E+C23002A_018E,
	       BlackEmp_State = C23002B_007E+C23002B_012E+C23002B_020E+C23002B_025E+C23002B_005E+C23002B_018E,
	       AsianEmp_State = C23002D_007E+C23002D_012E+C23002D_020E+C23002D_025E+C23002D_005E+C23002D_018E,
	       HispanicEmp_State = C23002I_007E+C23002I_012E+C23002I_020E+C23002I_025E+C23002I_005E+C23002I_018E,
	       TwoOrMoreEmp_State = C23002G_007E+C23002G_012E+C23002G_020E+C23002G_025E+C23002G_005E+C23002G_018E,
         WhiteEmpPer_State = (C23002A_007E+C23002A_012E+C23002A_020E+C23002A_025E+C23002A_005E+C23002A_018E)/B23001_001E,
	       BlackEmpPer_State = (C23002B_007E+C23002B_012E+C23002B_020E+C23002B_025E+C23002B_005E+C23002B_018E)/B23001_001E,
	       AsianEmpPer_State = (C23002D_007E+C23002D_012E+C23002D_020E+C23002D_025E+C23002D_005E+C23002D_018E)/B23001_001E,
	       HispanicEmpPer_State = (C23002I_007E+C23002I_012E+C23002I_020E+C23002I_025E+C23002I_005E+C23002I_018E)/B23001_001E,
	       TwoOrMoreEmpPer_State = (C23002G_007E+C23002G_012E+C23002G_020E+C23002G_025E+C23002G_005E+C23002G_018E)/B23001_001E) %>%
	select(WhiteEmp_State, BlackEmp_State, AsianEmp_State, HispanicEmp_State, TwoOrMoreEmp_State,
	       WhiteEmpPer_State, BlackEmpPer_State, AsianEmpPer_State, HispanicEmpPer_State, TwoOrMoreEmpPer_State) %>%
  cbind(Emp.Race.BG) 

Each_State <- Emp.Race.State 

#############################################   Employee Education    ########################################################
# Employee education at Block Group level
Emp.Educ.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B16010_003", # Less than high school graduate in labor force
														              "B16010_016", # High school graduate in labor force 
														              "B16010_029", # Some college or associate's degree in labor force
														              "B16010_042"), # Bachelor's degree or higher in labor force
												
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID) %>%
	mutate(LessThanHSLabor_BG = B16010_003E,
	       HSGradLabor_BG = B16010_016E,
	       SomeCollLabor_BG = B16010_029E,
	       BachOrHigherLabor_BG = B16010_042E) %>%
	select(BG_ID_10 ,LessThanHSLabor_BG, HSGradLabor_BG, SomeCollLabor_BG, BachOrHigherLabor_BG) %>%
  left_join(Each_State, Emp.Educ.BG, by="BG_ID_10")

# Employee education at State level
Emp.Educ.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B16010_003", # Less than high school graduate in labor force
														              "B16010_016", # High school graduate in labor force 
														              "B16010_029", # Some college or associate's degree in labor force
														              "B16010_042"), # Bachelor's degree or higher in labor force
												
														keep_geo_vars = T) %>%
	mutate(LessThanHSLabor_State = B16010_003E,
	       HSGradLabor_State = B16010_016E,
	       SomeCollLabor_State = B16010_029E,
	       BachOrHigherLabor_State = B16010_042E) %>%
	select(LessThanHSLabor_State, HSGradLabor_State, SomeCollLabor_State, BachOrHigherLabor_State) %>%
  cbind(Emp.Educ.BG) 

Each_State <- Emp.Educ.State 

#############################################    Employee Sex   #############################################################
# Employee gender at Block Group level
Emp.Sex.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B23001_005", # Employed males
														              "B23001_007", 
														              "B23001_012",
														              "B23001_014",
														              "B23001_019",
														              "B23001_021",
														              "B23001_026",
														              "B23001_028",
														              "B23001_033",
														              "B23001_035",
														              "B23001_040",
														              "B23001_042",
														              "B23001_047",
														              "B23001_049",
														              "B23001_054",
														              "B23001_056",
														              "B23001_061",
														              "B23001_063",
														              "B23001_068",
														              "B23001_070",
														              "B23001_075",
														              "B23001_080",
														              "B23001_085",
														              "B23001_091", # Employed females
														              "B23001_093",
														              "B23001_098",
														              "B23001_100",
														              "B23001_105",
														              "B23001_107",
														              "B23001_112",
														              "B23001_114",
														              "B23001_119",
														              "B23001_121",
														              "B23001_126",
														              "B23001_128",
														              "B23001_133",
														              "B23001_135",
														              "B23001_140",
														              "B23001_142",
														              "B23001_147",
														              "B23001_149",
														              "B23001_154",
														              "B23001_156",
														              "B23001_161",
														              "B23001_166",
														              "B23001_171"), # Total employees
														keep_geo_vars = T) %>%
  rename(BG_ID_10 = GEOID) %>%
	mutate(EmpMale_BG = B23001_005E + B23001_007E + B23001_012E + B23001_014E + B23001_019E + B23001_021E + B23001_026E + B23001_028E + B23001_033E + B23001_035E + B23001_040E + B23001_042E + B23001_047E + B23001_049E + B23001_054E + B23001_056E + B23001_061E + B23001_063E + B23001_068E+ B23001_070E + B23001_075E + B23001_080E + B23001_085E,
	  EmpFemale_BG = B23001_091E + B23001_093E + B23001_098E + B23001_100E + B23001_105E + B23001_107E + B23001_112E + B23001_114E + B23001_119E + B23001_121E + B23001_126E + B23001_128E + B23001_133E + B23001_135E + B23001_140E + B23001_142E + B23001_147E + B23001_149E + B23001_154E + B23001_156E + B23001_161E + B23001_166E + B23001_171E,
	  TotalEmp_BG = EmpMale_BG + EmpFemale_BG) %>%
	select(BG_ID_10, EmpMale_BG, EmpFemale_BG, TotalEmp_BG)%>%
  left_join(Each_State, Emp.Sex.BG, by="BG_ID_10")


# Employee gender at State level
Emp.Sex.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B23001_005", # Employed males
														              "B23001_007",
														              "B23001_012",
														              "B23001_014",
														              "B23001_019",
														              "B23001_021",
														              "B23001_026",
														              "B23001_028",
														              "B23001_033",
														              "B23001_035",
														              "B23001_040",
														              "B23001_042",
														              "B23001_047",
														              "B23001_049",
														              "B23001_054",
														              "B23001_056",
														              "B23001_061",
														              "B23001_063",
														              "B23001_068",
														              "B23001_070",
														              "B23001_075",
														              "B23001_080",
														              "B23001_085",
														              "B23001_091",
														              "B23001_093", # Employed females
														              "B23001_098",
														              "B23001_100",
														              "B23001_105",
														              "B23001_107",
														              "B23001_112",
														              "B23001_114",
														              "B23001_119",
														              "B23001_121",
														              "B23001_126",
														              "B23001_128",
														              "B23001_133",
														              "B23001_135",
														              "B23001_140",
														              "B23001_142",
														              "B23001_147",
														              "B23001_149",
														              "B23001_154",
														              "B23001_156",
														              "B23001_161",
														              "B23001_166",
														              "B23001_171"), # Total employees
														keep_geo_vars = T) %>%
	mutate(EmpMale_State = B23001_005E + B23001_007E + B23001_012E + B23001_014E + B23001_019E + B23001_021E + B23001_026E + B23001_028E + B23001_033E + B23001_035E + B23001_040E + B23001_042E + B23001_047E + B23001_049E + B23001_054E + B23001_056E + B23001_061E + B23001_063E + B23001_068E + B23001_070E + B23001_075E + B23001_080E + B23001_085E,
	  EmpFemale_State = B23001_091E + B23001_093E + B23001_098E + B23001_100E + B23001_105E + B23001_107E + B23001_112E + B23001_114E + B23001_119E + B23001_121E + B23001_126E + B23001_128E + B23001_133E + B23001_135E + B23001_140E + B23001_142E + B23001_147E + B23001_149E + B23001_154E + B23001_156E + B23001_161E + B23001_166E + B23001_171E,
	  TotalEmp_state = EmpMale_State+EmpFemale_State) %>%
	select(EmpMale_State, EmpFemale_State, TotalEmp_state) %>%
cbind(Emp.Sex.BG) 

Each_State <- Emp.Sex.State

##########################################################################################################################

                                                #----------------------#
                                                #    FOOD INSECURITY   #
                                                #----------------------#

####################################################  SNAP Recipients  ###################################################         

# SNAP Recipients at Block Group level
Snap.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B22001_002", # Household received Food Stamps/SNAP in the past 12 months
														"B22001_001"), # Total 
														keep_geo_vars = T) %>%
	rename(BG_ID_10 = GEOID,
	       SnapRec_BG = B22001_002E/B22001_001E) %>%
	select(BG_ID_10, SnapRec_BG) %>%
  left_join(Each_State, Snap.BG, by="BG_ID_10")

# SNAP Recipients at State level
Snap.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B22001_002", # Household received Food Stamps/SNAP in the past 12 months
														"B22001_001"), # Total 
														keep_geo_vars = T) %>%
	mutate(SnapRec_State = B22001_002E/B22001_001E) %>%
	select(SnapRec_State) %>%
  cbind(Snap.BG) 

Each_State <- Snap.State 

#######################################################################################################################################

                                                #----------------------#
                                                #       HOUSING        #
                                                #----------------------#

######################   Proportion of Renters to Owners, Home Values   ########################################

# Proportion of Renters to Owners and Home Values at Block Group level
Housing.BG <- tidycensus::get_acs(geography = "block group",
															 survey="acs5",
															 state=i,
															 year = endyr,
															 output = "wide",
															 variables = c("B25009_001", # Total Occupied Housing Units
															 	"B25009_002", # Total Owner Occupied Housing Units
															 	"B25009_010", # Total Renter Occupied Housing Units
															 	"B25077_001", # Median Home Value
															 	"B25082_001", # Aggregate value
															 	"B25003_002"), # Owner occupied
															 keep_geo_vars = T) %>%
	rename(MedianHValue_BG = B25077_001E,
	       AvgHValue_BG = B25082_001E / B25003_002E,
				 BG_ID_10 = GEOID) %>%
	mutate(RentersPer_BG = B25009_010E/B25009_001E,
				 HomeOwnPer_BG = B25009_002E/B25009_001E,
				 RentersToOwners_BG = B25009_010E/B25009_002E) %>%
	select(BG_ID_10,RentersPer_BG, HomeOwnPer_BG, RentersToOwners_BG, MedianHValue_BG, AvgHValue_BG) %>%
  left_join(Each_State, Housing.BG, by="BG_ID_10")

# Proportion of Renters to Owners and Home Values at State level
Housing.State <- tidycensus::get_acs(geography = "state",
															 survey="acs5",
															 state=i,
															 year = endyr,
															 output = "wide",
															 variables = c("B25009_001", # Total Occupied Housing Units
															 	"B25009_002", # Total Owner Occupied Housing Units
															 	"B25009_010", # Total Renter Occupied Housing Units
															 	"B25077_001", # Median Home Value
															 	"B25082_001", # Aggregate value
															 	"B25003_002"), # Owner occupied
															 keep_geo_vars = T) %>%
	mutate(MedianHValue_State = B25077_001E,
	       AvgHValue_State = B25082_001E / B25003_002E,
	       RentersPer_State = B25009_010E/B25009_001E,
				 HomeOwnPer_State = B25009_002E/B25009_001E,
				 RentersToOwners_State = B25009_010E/B25009_002E) %>%
	select(RentersPer_State, HomeOwnPer_State, RentersToOwners_State, MedianHValue_State, AvgHValue_State) %>%
  cbind(Housing.BG) 

Each_State <- Housing.State


#########################################      Duration of Occupancy    ####################################################

# Duration of Occupancy at Block Group level
Dur.Occ.BG <- tidycensus::get_acs(geography = "block group",
															 survey="acs5",
															 state=i,
															 year = endyr,
															 output = "wide",
															 variables = c("B25039_001", # Median Year Householder Moved Into Unit by Tenure
															 	"B25039_002", # Median Year Householder Moved Into Unit by Tenure (Owner)
															 	"B25039_003"), # Median Year Householder Moved Into Unit by Tenure (Renter)
															 keep_geo_vars = T) %>%
	rename(MedYrMovedIn_BG = B25039_001E, # I'm not sure if I should substract this value from 2018
				 MedYrRentMovedIn_BG = B25039_003E,
				 MedYrOwnMovedIn_BG = B25039_002E,
				 BG_ID_10 = GEOID) %>%
	select(BG_ID_10, MedYrMovedIn_BG, MedYrRentMovedIn_BG, MedYrOwnMovedIn_BG) %>%
  left_join(Each_State, Dur.Occ.BG, by="BG_ID_10")

# Duration of Occupancy at State level
Dur.Occ.State <- tidycensus::get_acs(geography = "state",
															 survey="acs5",
															 state=i,
															 year = endyr,
															 output = "wide",
															 variables = c("B25039_001", # Median Year Householder Moved Into Unit by Tenure
															 	"B25039_002", # Median Year Householder Moved Into Unit by Tenure (Owner)
															 	"B25039_003"), # Median Year Householder Moved Into Unit by Tenure (Renter)
															 keep_geo_vars = T) %>%
	mutate(MedYrMovedIn_State = B25039_001E, # I'm not sure if I should substract this value from 2018
				 MedYrRentMovedIn_State = B25039_003E,
				 MedYrOwnMovedIn_State = B25039_002E) %>%
	select(MedYrMovedIn_State, MedYrRentMovedIn_State, MedYrOwnMovedIn_State) %>%
 cbind(Dur.Occ.BG) 

Each_State <- Dur.Occ.State


##############################################   Cost Burdened Occupants   ##################################

# Cost Burdened Occupants at Block Group level
CostBurdened.BG <- tidycensus::get_acs(geography = "block group",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B25095_006", # Household income by selected monthly owner Costs as a percentage of household income
														              # Less than $10,000 (30 to 34.9 percent)
														              "B25095_007", # Less than $10,000 (35 to 39.9 percent)
														              "B25095_008", # Less than $10,000 (40 to 49.9 percent)
														              "B25095_009", # Less than $10,000 (50 percent or more)
														              "B25095_015", # $10,000 to $19,999 (30 to 34.9 percent)
														              "B25095_016", # $10,000 to $19,999 (35 to 39.9 percent)
														              "B25095_017", # $10,000 to $19,999 (40 to 49.9 percent)
														              "B25095_018", # $10,000 to $19,999 (50 percent or more)
														              "B25095_024", # $20,000 to $34,999 (30 to 34.9 percent)
														              "B25095_025", # $20,000 to $34,999 (35 to 39.9 percent)
														              "B25095_026", # $20,000 to $34,999 (40 to 49.9 percent)
														              "B25095_027", # $20,000 to $34,999 (50 percent or more)
														              "B25095_033", # $35,000 to $49,999 (30 to 34.9 percent)
														              "B25095_034", # $35,000 to $49,999 (35 to 39.9 percent)
														              "B25095_035", # $35,000 to $49,999 (40 to 49.9 percent)
														              "B25095_036", # $35,000 to $49,999 (50 percent or more)
														              "B25095_042", # $50,000 to $74,999 (30 to 34.9 percent)
														              "B25095_043", # $50,000 to $74,999 (35 to 39.9 percent)
														              "B25095_044", # $50,000 to $74,999 (40 to 49.9 percent)
														              "B25095_045", # $50,000 to $74,999 (50 percent or more)
														              "B25095_051", # $75,000 to $99,999 (30 to 34.9 percent)
														              "B25095_052", # $75,000 to $99,999 (35 to 39.9 percent)
														              "B25095_053", # $75,000 to $99,999 (40 to 49.9 percent)
														              "B25095_054", # $75,000 to $99,999 (50 percent or more)
														              "B25095_060", # $100,000 to $149,999 (30 to 34.9 percent)
														              "B25095_061", # $100,000 to $149,999 (35 to 39.9 percent)
														              "B25095_062", # $100,000 to $149,999 (40 to 49.9 percent)
														              "B25095_063", # $100,000 to $149,999 (50 percent or more)
														              "B25095_069", # $150,000 or more (30 to 34.9 percent)
														              "B25095_070", # $150,000 or more (35 to 39.9 percent)
														              "B25095_071", # $150,000 or more (40 to 49.9 percent)
														              "B25095_072", # $150,000 or more (50 percent or more)
														              "B25095_001"), # Total 
														keep_geo_vars = T) %>% rename(BG_ID_10 = GEOID) %>%
	mutate(CostBurdened_BG = B25095_006E+B25095_007E+B25095_008E+B25095_009E+B25095_015E+B25095_016E+B25095_017E+B25095_018E+
	       B25095_024E+B25095_025E+B25095_026E+B25095_027E+B25095_033E+B25095_034E+B25095_035E+B25095_036E+B25095_042E+B25095_043E+B25095_044E+B25095_045E+B25095_051E+B25095_052E+B25095_053E+B25095_054E+B25095_060E+B25095_061E+B25095_062E+B25095_063E+B25095_069E+B25095_070E+B25095_071E+B25095_072E) %>%
	select(BG_ID_10, CostBurdened_BG) %>%
  left_join(Each_State, CostBurdened.BG, by="BG_ID_10")

# Cost Burdened Occupants at State level
CostBurdened.State <- tidycensus::get_acs(geography = "state",
														survey="acs5",
														state=i,
														year = endyr,
														output = "wide",
														variables = c("B25095_006", # Household income by selected monthly owner Costs as a percentage of household income
														              # Less than $10,000 (30 to 34.9 percent)
														              "B25095_007", # Less than $10,000 (35 to 39.9 percent)
														              "B25095_008", # Less than $10,000 (40 to 49.9 percent)
														              "B25095_009", # Less than $10,000 (50 percent or more)
														              "B25095_015", # $10,000 to $19,999 (30 to 34.9 percent)
														              "B25095_016", # $10,000 to $19,999 (35 to 39.9 percent)
														              "B25095_017", # $10,000 to $19,999 (40 to 49.9 percent)
														              "B25095_018", # $10,000 to $19,999 (50 percent or more)
														              "B25095_024", # $20,000 to $34,999 (30 to 34.9 percent)
														              "B25095_025", # $20,000 to $34,999 (35 to 39.9 percent)
														              "B25095_026", # $20,000 to $34,999 (40 to 49.9 percent)
														              "B25095_027", # $20,000 to $34,999 (50 percent or more)
														              "B25095_033", # $35,000 to $49,999 (30 to 34.9 percent)
														              "B25095_034", # $35,000 to $49,999 (35 to 39.9 percent)
														              "B25095_035", # $35,000 to $49,999 (40 to 49.9 percent)
														              "B25095_036", # $35,000 to $49,999 (50 percent or more)
														              "B25095_042", # $50,000 to $74,999 (30 to 34.9 percent)
														              "B25095_043", # $50,000 to $74,999 (35 to 39.9 percent)
														              "B25095_044", # $50,000 to $74,999 (40 to 49.9 percent)
														              "B25095_045", # $50,000 to $74,999 (50 percent or more)
														              "B25095_051", # $75,000 to $99,999 (30 to 34.9 percent)
														              "B25095_052", # $75,000 to $99,999 (35 to 39.9 percent)
														              "B25095_053", # $75,000 to $99,999 (40 to 49.9 percent)
														              "B25095_054", # $75,000 to $99,999 (50 percent or more)
														              "B25095_060", # $100,000 to $149,999 (30 to 34.9 percent)
														              "B25095_061", # $100,000 to $149,999 (35 to 39.9 percent)
														              "B25095_062", # $100,000 to $149,999 (40 to 49.9 percent)
														              "B25095_063", # $100,000 to $149,999 (50 percent or more)
														              "B25095_069", # $150,000 or more (30 to 34.9 percent)
														              "B25095_070", # $150,000 or more (35 to 39.9 percent)
														              "B25095_071", # $150,000 or more (40 to 49.9 percent)
														              "B25095_072", # $150,000 or more (50 percent or more)
														              "B25095_001"), # Total 
														keep_geo_vars = T) %>% 
	mutate(CostBurdened_State = B25095_006E+B25095_007E+B25095_008E+B25095_009E+B25095_015E+B25095_016E+B25095_017E+B25095_018E+
	       B25095_024E+B25095_025E+B25095_026E+B25095_027E+B25095_033E+B25095_034E+B25095_035E+B25095_036E+B25095_042E+B25095_043E+B25095_044E+B25095_045E+B25095_051E+B25095_052E+B25095_053E+B25095_054E+B25095_060E+B25095_061E+B25095_062E+B25095_063E+B25095_069E+B25095_070E+B25095_071E+B25095_072E) %>%
	select(CostBurdened_State) %>%
 cbind(CostBurdened.BG) 

Each_State <- CostBurdened.State

### Final Maine dataset
States_Data[[j]] <- Each_State
j <- j+1

}
States_Data

```

```{r}
#library(totalcensus)
#set_path_to_census("~/Desktop//my_census_data")
#mixed <- read_acs5year(
   # year = 2018,
   # states = "MA",
   # table_contents = 
        #"B14001_002",
    #areas = 
       # "Pittsfield city, MA",
   # summary_level = "tract"

#mixed
#sum(mixed$population)

#search_fips()
```

```{r}
library(dplyr)
#States.csv <- select(Each_State2, c(CostBurdened_State,CostBurdenedPer,MedYrMovedIn_State,MedYrRentMovedIn_State, MedYrOwnMovedIn_State,RentersPer_State,HomeOwnPer_State,RentersToOwners_State, MedianHValue_State, AvgHValue_State, SnapRec_State, EmpMale_State, EmpFemale_State, TotalEmp_state, EmpMalePer, EmpFemalePer, LessThanHSLabor_State, HSGradLabor_State, SomeCollLabor_State, BachOrHigherLabor_State, LessThanHSLaborPer, HSGradLaborPer, SomeCollLaborPer, BachOrHigherLaborPer, WhiteEmp_State, BlackEmp_State, AsianEmp_State, HispanicEmp_State,TwoOrMoreEmp_State,WhiteEmpPer_State,BlackEmpPer_State,AsianEmpPer_State,HispanicEmpPer_State,TwoOrMoreEmpPer_State,AgeEmpU29_State,AgeEmp3054_State,AgeEmpO55_State,AgeEmpU29Per_State,AgeEmp3054Per_State,AgeEmpO55Per_State,MedEarning_State,Agriculture_State,Construction_State,Manufacturing_State,WholesaleTrade_State,RetailTrade_State,Transportation_State,Information_State,Finance_Ins_State,Professional_State,Educ_Health_SocSvcs_State,RecreationEtc_State,OtherIndustries_State,PublicAdmin_State,MaleNCAIS_State,FemaleNCAIS_State,MaleNCAISPer_State,FemaleNCAISPer_State,EmpRate_State,UnempRate_State,EmployedCLF_State,UnemployedCLF_State,LabForce_State,LabForcePer_State,CivLabForce_State,CivLabForcePer_State,Military_State,MilitaryPer_State,TotalWorkers_State,WorkStateCounty_State,WorkStateCountyPer_State,WorkPlace_State,WorkPlacePer_State,NumJobs_State,EnrolPK12_State,OldAlonePer_State,FamPovPer_State,PopPovPer_State,TotalPopPov_State,FemHeadPer_State,MaleHeadPer_State,LessThanHS_State,HSGrad_State,SomeColl_State,Bach_State,Master_State,Prof_State,Doc_State,LessThanHSPer_State,HSGradPer_State,SomeCollPer_State,BachPer_State,MasterPer_State,ProfPer_State,DocPer_State,AveHouseH_State,Female_State,Male_State,SexRatio_State,White_State,Black_State,Asian_State,Hispanic_State,TwoOrMore_State,MedHouseIncome_State,AgeU18_State,Age1834_State,Age3564_State,AgeO65_State,State,TotalPop_State,AgeU18Per_State,Age1834Per_State,Age3564Per_State,AgeO65Per_State,WhitePer_State,BlackPer_State,AsianPer_State,HispanicPer_State,TwoOrMorePer_State,TwoOrMorePer_State,FemalePer_State,MalePer_State,TotalPop_State))

#States.csv[1,]
```

